### ISSUE TITLE
Potentially show new errInfo data in validation errors

### ISSUE THREAD

**Issue by atlantis** [elbywan/cryomongo#15]
Not sure exactly how you'd want to implement this, but the new specific validation errors Mongo 5 gives are super helpful, so for my own use I've just added:

#Patch cryomongo /lib/cryomongo/src/cryomongo/error.cr : 164
if info = error["errInfo"]?.as?(BSON)
  puts "Mongo errInfo: \n" + info.to_json
end

The errInfo is deeply nested an unpredictable, so to add it officially to the library should the Error perhaps have `property info : BSON?`?

**Comment by elbywan** [comment]
Hey @atlantis 👋 

> the new specific validation errors Mongo 5 gives are super helpful

True, thanks for pointing this out!

> The errInfo is deeply nested an unpredictable, so to add it officially to the library should the Error perhaps have property info : BSON

I added a `@details` getter populated by the `errInfo` field in this commit: https://github.com/elbywan/cryomongo/commit/9f771262a8b0cf8963f878e1d63836a0fb97fdcd and released `v0.3.11` which includes the change.

**Comment by atlantis** [comment]
Awesome, thanks so much!Sent from my iPhoneOn Oct 8, 2022, at 11:03 AM, Julien Elbaz ***@***.***> wrote:﻿
Hey @atlantis 👋

the new specific validation errors Mongo 5 gives are super helpful

True, thanks for pointing this out!

The errInfo is deeply nested an unpredictable, so to add it officially to the library should the Error perhaps have property info : BSON

I added a @details getter populated by the errInfo field in this commit: 9f77126 and released v0.3.11 which includes the change.
