### ISSUE TITLE
Error: undefined constant BSON::Options

### ISSUE THREAD

**Issue by kebasyaty** [elbywan/cryomongo#17]
Hi!
Recently I encountered this problem.
During compilation it gives the following error:
In lib/cryomongo/src/cryomongo/sessions/sessions.cr:13:5

 13 | @[BSON::Options(camelize: "lower")]
        ^------------
Error: undefined constant BSON::Options

Perhaps these are some changes in BSON?

**Comment by elbywan** [comment]
Hey @kebasyaty,

> Perhaps these are some changes in BSON?

Yes it got broken by the latest crystal release and I forgot to tag the library after fixing the issue, it should be all good now (after running`shards update`).

**Comment by kebasyaty** [comment]
Thank you very much!
Everything works perfectly!!!
I'm closing the issue.
