### ISSUE TITLE
SASL SCRAM-SHA-256 authentication failure on mongo 4.2.7

### ISSUE THREAD

**Issue by atlantis** [elbywan/cryomongo#2]
Hey there!  Great libraries - I discovered cryomongo and moongoon right before deploying a crystal app to production, and it's so much better I'm rewriting my app to use them instead of another ORM.

I'm actually adding a few things like validations, dirty field tracking, and more BSON::ObjectId id flexibility to moongoon (pull requests forthcoming), but during testing for that I ran into the current error (using the docker mongo 4.2.7 image):

`mongo_1          | 2020-10-14T04:32:02.212+0000 I  ACCESS   [conn69] SASL SCRAM-SHA-256 authentication failed for tests on admin from client 172.18.0.1:38618 ; AuthenticationFailed: SCRAM authentication failed, storedKey mismatch
`
However, I've confirmed by using the shell that I'm using the correct password and the user exists in the admin database.  

I've traced the problem to scram.cr, where Step 3 results in a failure.  I've confirmed that @iterations is set to 15000 (the default) and the @client_key contains data, so I'm not quite sure what the problem is... it seems to be generating a slightly malformed message.  

When I enter:

username: tests
password: t

...it results in the following (for a single run.. as expected, the output does change each attempt):

auth_message;: n=tests,r=4XNLkk9/2lPlb8oXoiD13w==,r=4XNLkk9/2lPlb8oXoiD13w==4sfRkRvXuKt6v0ddInXSehaJ49sXoe1F,s=Z1msBKGAb6RJbh/73SgPH7Qq5y6ynXuHPPuwtQ==,i=15000,c=biws,r=4XNLkk9/2lPlb8oXoiD13w==4sfRkRvXuKt6v0ddInXSehaJ49sXoe1F

payload: Bytes[99, 61, 98, 105, 119, 115, 44, 114, 61, 52, 88, 78, 76, 107, 107, 57, 47, 50, 108, 80, 108, 98, 56, 111, 88, 111, 105, 68, 49, 51, 119, 61, 61, 52, 115, 102, 82, 107, 82, 118, 88, 117, 75, 116, 54, 118, 48, 100, 100, 73, 110, 88, 83, 101, 104, 97, 74, 52, 57, 115, 88, 111, 101, 49, 70, 44, 112, 61, 105, 51, 72, 82, 65, 53, 81, 72, 79, 71, 115, 115, 77, 83, 101, 105, 90, 87, 99, 109, 109, 122, 67, 112, 70, 107, 74, 52, 53, 85, 113, 65, 82, 122, 103, 86, 77, 112, 117, 101, 121, 115, 119, 61]

Is there any more debugging information I can provide that would be helpful?

**Comment by atlantis** [comment]
Just tested on docker mongo:4.2.10 and same issue...

**Comment by elbywan** [comment]
Hi @atlantis, thanks for reporting the issue!

> Hey there! Great libraries - I discovered cryomongo and moongoon right before deploying a crystal app to production, and it's so much better I'm rewriting my app to use them instead of another ORM.

Thanks!

> SASL SCRAM-SHA-256 authentication failed

There are definitely issues with sha256, I'll try to fix that today.

In the meantime, you can use `&authMechanism=SCRAM-SHA-1` to temporarily switch to sha-1.

**Comment by elbywan** [comment]
@atlantis I pushed a fix (https://github.com/elbywan/cryomongo/commit/7f90590500e1599433f3ef7cebfb4b41d778c9c1), released with 📦 `v0.2.3` that should hopefully fix the problem!

**Comment by atlantis** [comment]
Confirmed that fixed it - thanks much!
