### ISSUE TITLE
Error: can't find file 'dns'

### ISSUE THREAD

**Issue by kebasyaty** [elbywan/cryomongo#20]
Hello!
Please return `dns`.

Run crystal spec
In lib/cryomongo/src/cryomongo/uri/srv.cr:1:1

 1 | require "dns"
     ^
Error: can't find file 'dns'

Thanks in advance!

**Comment by elbywan** [comment]
Hey, did you run `shards install`?

```
shards install
Resolving dependencies
Fetching https://github.com/elbywan/cryomongo.git
Fetching https://github.com/elbywan/bson.cr.git
Fetching https://github.com/spider-gazelle/dns.git
Installing bson (0.3.6)
Installing dns (0.1.0 at e5821f0)
Installing cryomongo (0.3.12)
Writing shard.lock
```

**Comment by kebasyaty** [comment]
Thank you very much !!!
Now everything works !

P.S.
Yes, I ran shards install and it didn't work, but now it works.
