### ISSUE TITLE
Increasing number of Mongo connections over time

### ISSUE THREAD

**Issue by atlantis** [elbywan/cryomongo#3]
So I may just be doing something dumb here, but I'm using https://kemalcr.com/ and initialize a single cryomongo connection that's then shared by every request (kemal uses fibers so there's only one executing at a time).  What's worrisome is that over time Mongo Atlas reports that connections stack up until they hit the max allowed and then my app crashes and restarts.

![Screen Shot 2020-11-04 at 3 54 49 PM](https://user-images.githubusercontent.com/134251/98180834-d3217b00-1eb6-11eb-96fe-e56551c70348.png)

I'm running at the DEBUG log level I'm not seeing any errors at all... could there be some sort of reconnect code in cryomongo that keeps old connections open but opens new ones perhaps?

Sorry there's not an easily way to immediately reproduce this issue... it stacks up over time.  I'll investigate ways of making the problem show up faster in a test app...

**Comment by elbywan** [comment]
Hmm this is weird `cryomongo` uses the `DB::Pool` class from the `crystal-db` shard which is managing a pool of 100 maximum connections to a single mongo instance (by default).

I'll perform some tests to try to reproduce the problem. 

On a side note I found an issue with cursors and implicit sessions that I'll commit on master, but I don't think that it is related.

**Comment by elbywan** [comment]
> I'll perform some tests to try to reproduce the problem.

Ok so there are definitely connection leaks. I think I found the reason I'll work on fixing this today.

**Comment by elbywan** [comment]
Allright found the issue and pushed a fix on master, I will release a new version as soon as I get the green light from the CI. 🎉
