### ISSUE TITLE
Bug in macro generation code

### ISSUE THREAD

**Issue by straight-shoota** [elbywan/cryomongo#7]
The following lines probably don't do what they're supposed to do:

https://github.com/elbywan/cryomongo/blob/20489ad9490af4312cc2ae8f92a3519c20fe12ca/src/cryomongo/commands/session/start_session.cr#L25-L27

`id : String` just declares a local variable in the top level scope (actually in `ID` scope, but local variables inside types are shared with the top level).

Because of a compiler bug this causes programs using this shard to fail to build with `--debug` flag, see https://github.com/crystal-lang/crystal/issues/9882

**Comment by elbywan** [comment]
@straight-shoota Thanks for reporting the issue! 👍 

> The following lines probably don't do what they're supposed to do:

Yes indeed this is a typo, it should be `property id : String`.
