### ISSUE TITLE
Default database

### ISSUE THREAD

**Issue by pyrsmk** [elbywan/cryomongo#8]
Hi, and thanks for your work ;)

I saw that you can instantiate the object with the database name directly in the MongoDB URL `Mongo::Client.new("mongodb://address:port/database")` but it seems that we need to retrieve the database first anyway with `client["database_name"]`.

This is not really handy. Since the MongoDB URL can be passed from the command line then I need to parse the URL to know what is the name of the database I need to access.

Is there a way to retrieve the database that is set in the defined URL easily?

**Comment by elbywan** [comment]
Hey @pyrsmk,

> Hi, and thanks for your work ;)

Thanks ❤️.

> This is not really handy.

I agree it's not really convenient.

> Is there a way to retrieve the database that is set in the defined URL easily?

I just pushed a commit that adds two methods to the `Client` class to expose the [default auth database](https://github.com/mongodb/specifications/blob/master/source/connection-string/connection-string-spec.rst#auth-database-optional) as a `String` and as a nillable `Database` instance.

```crystal
client = Mongo::Client.new("mongodb://localhost:27017/database")
# An instance pointing to the "database" db.
# Can be Nil because the default auth db part of the uri is optional.
database : Database? = client.default_database 
# To retrieve the auth db as a String.
puts client.default_auth_db 
# => "database"
```

I'll release a new version as soon as the CI goes green 🟢.

**Comment by pyrsmk** [comment]
Awesome! Thanks a lot for your reactivity 🎉
